import type { Metadata } from "next";
import NavBar from "@/components/NavBar";
import "./globals.css";


export const metadata: Metadata = {
  title: "Coltive ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-0 p-0">
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
